project:
  type: website
  
  output-dir: docs
  execute-dir: project
  render:
    - "*.qmd"
    - "!scratch_notebook.qmd"
    - "!04_interact_with_csv_using_ollama.qmd"

website:
  page-navigation: true
  title: AI Agents and LLMs
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Interact with local LLMs through Ollama"
        contents:
          - 01_use_ollama_API.qmd
          - 02_use_ollama_python_library.qmd
      - text: "Interact with local LLMs using langchain"
        href: 03_use_ollama_through_langchain.qmd
      - section: LangGraph for building AI agents
        contents:
          - text: "LangGraph Basics"
            href: 05_graph_basics_langgraph.qmd
          - text: "Using local chat models in LangGraph"
            href: 06_using_local_chat_models_in_langgraph.qmd

format:
  html:
    theme: yeti
    toc: true
